// ─── reports.js ──────────────────────────────────────────────────
// Handles: loading monthly summary, category table, PDF export
// ─────────────────────────────────────────────────────────────────

let currentSummary = null; // Store for PDF export

document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("report-month").value = getCurrentMonth();
  loadReport();
});

function getCurrentMonth() {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
}

// ─── LOAD REPORT ──────────────────────────────────────────────────
async function loadReport() {
  const month   = document.getElementById("report-month").value;
  const summary = await apiGetSummary(month);
  currentSummary = summary; // Save for PDF

  // Update summary cards
  document.getElementById("r-income").textContent  = `₹${(summary.total_income  || 0).toLocaleString()}`;
  document.getElementById("r-expense").textContent = `₹${(summary.total_expense || 0).toLocaleString()}`;
  document.getElementById("r-balance").textContent = `₹${(summary.balance       || 0).toLocaleString()}`;

  // Build category breakdown table
  const tbody   = document.getElementById("category-tbody");
  tbody.innerHTML = "";

  const categories = summary.category_totals || {};

  if (Object.keys(categories).length === 0) {
    tbody.innerHTML = `<tr><td colspan="2" style="text-align:center;color:var(--text-muted)">No expense data for this month</td></tr>`;
    return;
  }

  // Sort categories by amount (highest first)
  const sorted = Object.entries(categories).sort((a, b) => b[1] - a[1]);

  sorted.forEach(([cat, amount]) => {
    const row = document.createElement("tr");
    row.innerHTML = `
      <td>${categoryEmoji(cat)} ${capitalize(cat)}</td>
      <td>₹${amount.toLocaleString()}</td>
    `;
    tbody.appendChild(row);
  });
}

// ─── PDF EXPORT ───────────────────────────────────────────────────
// Uses jsPDF library to generate a downloadable PDF report
function exportPDF() {
  if (!currentSummary) {
    alert("Please load a report first.");
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc   = new jsPDF();
  const month = document.getElementById("report-month").value;

  // ── Header ──
  doc.setFontSize(22);
  doc.setTextColor(108, 99, 255); // accent color
  doc.text("ExpenseIQ – Monthly Report", 20, 20);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Month: ${month}`, 20, 32);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 40);

  // ── Summary ──
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Summary", 20, 55);

  doc.setFontSize(12);
  doc.setTextColor(50);
  doc.text(`Total Income:   Rs. ${(currentSummary.total_income  || 0).toLocaleString()}`, 20, 65);
  doc.text(`Total Expense:  Rs. ${(currentSummary.total_expense || 0).toLocaleString()}`, 20, 73);
  doc.text(`Balance:        Rs. ${(currentSummary.balance       || 0).toLocaleString()}`, 20, 81);

  // ── Category Breakdown ──
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Category Breakdown", 20, 96);

  const categories = Object.entries(currentSummary.category_totals || {})
    .sort((a, b) => b[1] - a[1]);

  let y = 106;
  doc.setFontSize(12);
  doc.setTextColor(50);

  if (categories.length === 0) {
    doc.text("No expense data available.", 20, y);
  } else {
    categories.forEach(([cat, amount]) => {
      doc.text(`${capitalize(cat)}: Rs. ${amount.toLocaleString()}`, 20, y);
      y += 8;
    });
  }

  // ── Footer ──
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by ExpenseIQ", 20, 285);

  // Save the PDF file
  doc.save(`ExpenseIQ_Report_${month}.pdf`);
}

// ─── HELPERS ─────────────────────────────────────────────────────
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
function categoryEmoji(cat) {
  const map = {
    food: "🍔", travel: "✈️", bills: "💡", shopping: "🛍️",
    health: "💊", education: "📚", other: "📦"
  };
  return map[cat] || "💰";
}
